version: "3.8"

services:
  mongodb-workshift:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb-workshift
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - backend-workshift
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-workshift:/data/db

  workshift-svc:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workshift-svc
    environment:
      - MONGODB_URL=${MONGOURL}
      - PORT=3011
    depends_on:
      - mongodb-workshift
    networks:
      - backend-workshift
      - rabbit-network
    ports:
      - "3011:3011"
    volumes:
      - .:/workshift-svc

volumes:
  mongo-data-workshift:

networks:
  backend-workshift:
    driver: bridge
  rabbit-network:
    external: true