apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: mongodb-workshift
  name: mongodb-workshift
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongodb-workshift
