apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongo-data-workshift
  name: mongo-data-workshift
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
