apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: workshift
  name: workshift-svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3011
      targetPort: 3011
  selector:
    io.kompose.service: workshift
